\copy continua FROM '/home/carlos/Downloads/TabelaContinuaCompleta.csv' DELIMITER ',' CSV HEADER;
\copy continua2010 FROM '/home/carlos/Downloads/continua2010.csv' DELIMITER ',' CSV HEADER;
\copy continua2011 FROM '/home/carlos/Downloads/continua2011.csv' DELIMITER ',' CSV HEADER;
\copy continua2012 FROM '/home/carlos/Downloads/continua2012.csv' DELIMITER ',' CSV HEADER;
\copy continua2013 FROM '/home/carlos/Downloads/continua2013.csv' DELIMITER ',' CSV HEADER;
\copy continua2014 FROM '/home/carlos/Downloads/continua2014.csv' DELIMITER ',' CSV HEADER;
\copy continua2015 FROM '/home/carlos/Downloads/continua2015.csv' DELIMITER ',' CSV HEADER;
\copy continua2016 FROM '/home/carlos/Downloads/continua2016.csv' DELIMITER ',' CSV HEADER;
\copy continua2017 FROM '/home/carlos/Downloads/continua2017.csv' DELIMITER ',' CSV HEADER;